<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Enums\ProductType;
use App\Enums\DiscountType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'id' => 1,
                'title' => 'Premium Wireless Headphones',
                'slug' => 'premium-wireless-headphones',
                'category_id' => 1,
                'subtitle' => 'Studio-quality sound with active noise cancellation',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 0,
                'discount' => 0,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Minimalist Leather Wallet',
                'slug' => 'minimalist-leather-wallet',
                'category_id' => 4,
                'subtitle' => 'Handcrafted full-grain leather with RFID protection',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 8999,
                'discount' => 15,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Designer Sunglasses',
                'slug' => 'designer-sunglasses',
                'category_id' => 4,
                'subtitle' => 'UV400 protection with polarized lenses',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 15999,
                'discount' => 20,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Mechanical Keyboard',
                'slug' => 'mechanical-keyboard',
                'category_id' => 1,
                'subtitle' => 'Custom switches with RGB backlighting',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 12999,
                'discount' => 500,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'Premium Coffee Maker',
                'slug' => 'premium-coffee-maker',
                'category_id' => 5,
                'subtitle' => 'Programmable brewing system with thermal carafe',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 24999,
                'discount' => 3000,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Wireless Charging Pad',
                'slug' => 'wireless-charging-pad',
                'category_id' => 1,
                'subtitle' => 'Fast charging for all Qi-enabled devices',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 3999,
                'discount' => 10,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'Stainless Steel Water Bottle',
                'slug' => 'stainless-steel-water-bottle',
                'category_id' => 4,
                'subtitle' => 'Double-wall insulated, keeps drinks cold for 24 hours',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 2499,
                'discount' => 250,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => 'Smart Watch Pro',
                'slug' => 'smart-watch-pro',
                'category_id' => 1,
                'subtitle' => 'Advanced health tracking with 7-day battery life',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 39999,
                'discount' => 15,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'title' => 'Leather Messenger Bag',
                'slug' => 'leather-messenger-bag',
                'category_id' => 4,
                'subtitle' => 'Professional laptop bag with multiple compartments',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 18999,
                'discount' => 2000,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => 'Studio Desk Lamp',
                'slug' => 'studio-desk-lamp',
                'category_id' => 5,
                'subtitle' => 'Adjustable LED with touch controls and USB charging',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 7999,
                'discount' => 800,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'title' => 'Ergonomic Office Chair',
                'slug' => 'ergonomic-office-chair',
                'category_id' => 2,
                'subtitle' => 'Full lumbar support with adjustable armrests',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 49999,
                'discount' => 5000,
                'discount_type' => DiscountType::FIXED->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'title' => 'Running Sneakers',
                'slug' => 'running-sneakers',
                'category_id' => 3,
                'subtitle' => 'Lightweight mesh design with responsive cushioning',
                'description' => 'Studio-quality sound with active noise cancellation',
                'image' => 'https://placehold.co/600x400',
                'status' => 1,
                'type' => ProductType::UPCOMING->value,
                'stock_level' => 0,
                'price' => 12999,
                'discount' => 20,
                'discount_type' => DiscountType::PERCENTAGE->value,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
